// Safe fallback mock data for seamless development and testing when backend is not seeded or running locally
export const devUserProfile = {
  user: {
    id: "dev-usr-01",
    full_name: "Alexander Wright",
    email: "alexander@grivi.io",
    role: "manager",

    language: "en",
    phone: "+1 (555) 234-8921",
    shop: {
      id: "shop-001",
      name: "Apex Gold & Collateral Pawn",
      phone: "+1 (555) 890-1234",
      email: "counter@apexpawn.com",
      address: "742 Evergreen Terrace, Suite 100, Springfield, OR 97477",
    },
  },
};

export const devDashboardStats = {
  stats: {
    total_loan_active: 184250,
    monthly_loan_given: 42500,
    total_active_tickets: 38,
    interest_collected: 4850,
    vault_items_count: 412,
    default_rate: 2.1,
  },
  top_customers: [
    { id: "cust-1", full_name: "Robert Downey", total_loan: 12500, active_tickets: 3 },
    { id: "cust-2", full_name: "Sophia Martinez", total_loan: 8400, active_tickets: 2 },
    { id: "cust-3", full_name: "David Miller", total_loan: 6200, active_tickets: 1 },
    { id: "cust-4", full_name: "James Wilson", total_loan: 4200, active_tickets: 2 },
    { id: "cust-5", full_name: "Elena Rostova", total_loan: 3100, active_tickets: 1 },
  ],
  recent_activity: [
    {
      id: "act-1",
      message: "New pawn ticket #T-4092 created for Robert Downey ($1,200.00)",
      createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
      user: { full_name: "Alexander Wright" },
    },
    {
      id: "act-2",
      message: "Interest payment of $36.00 recorded on ticket #T-3824",
      createdAt: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
      user: { full_name: "Sarah Jenkins" },
    },
    {
      id: "act-3",
      message: "Redemption processed for ticket #T-3644 ($850.00 settled)",
      createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
      user: { full_name: "Alexander Wright" },
    },
    {
      id: "act-4",
      message: "KYC verified and Aadhaar attached for Clara Oswald",
      createdAt: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
      user: { full_name: "Sarah Jenkins" },
    },
  ],
  gender_data: [
    { name: "Male", count: 48 },
    { name: "Female", count: 36 },
    { name: "Other", count: 6 },
  ],
  area_data: [
    { name: "Downtown / Central", count: 38 },
    { name: "Westside District", count: 24 },
    { name: "North Industrial", count: 18 },
    { name: "Suburban East", count: 10 },
  ],
};

export const devCustomers = [
  {
    id: "cust-1",
    full_name: "Robert Downey",
    phone_number: "9876543210",
    gender: "Male",
    address: { line1: "42 Beacon Hill", city: "Boston", pincode: "02108" },
    aadhaar_number: "987654321098",
    pan_number: "ABCDE1234F",
    customer_photo_url: "",
    createdAt: "2026-06-12T10:00:00.000Z",
    total_loan: 12500,
    active_tickets: 3,
  },
  {
    id: "cust-2",
    full_name: "Sophia Martinez",
    phone_number: "9845123456",
    gender: "Female",
    address: { line1: "128 Biscayne Blvd", city: "Miami", pincode: "33132" },
    aadhaar_number: "876543210987",
    pan_number: "FGHIJ5678K",
    customer_photo_url: "",
    createdAt: "2026-07-01T14:20:00.000Z",
    total_loan: 8400,
    active_tickets: 2,
  },
  {
    id: "cust-3",
    full_name: "David Miller",
    phone_number: "9712345678",
    gender: "Male",
    address: { line1: "800 Michigan Ave", city: "Chicago", pincode: "60611" },
    aadhaar_number: "765432109876",
    pan_number: "KLMNO9012P",
    customer_photo_url: "",
    createdAt: "2026-07-15T09:30:00.000Z",
    total_loan: 6200,
    active_tickets: 1,
  },
  {
    id: "cust-4",
    full_name: "Clara Oswald",
    phone_number: "9654321876",
    gender: "Female",
    address: { line1: "504 Congress Ave", city: "Austin", pincode: "78701" },
    aadhaar_number: "654321098765",
    pan_number: "PQRST3456U",
    customer_photo_url: "",
    createdAt: "2026-08-02T11:45:00.000Z",
    total_loan: 650,
    active_tickets: 1,
  },
  {
    id: "cust-5",
    full_name: "James Wilson",
    phone_number: "9543216789",
    gender: "Male",
    address: { line1: "1900 Elm Street", city: "Dallas", pincode: "75201" },
    aadhaar_number: "543210987654",
    pan_number: "UVWXY7890Z",
    customer_photo_url: "",
    createdAt: "2026-08-10T16:10:00.000Z",
    total_loan: 4200,
    active_tickets: 2,
  },
];

export const devPawnTickets = [
  {
    id: "pt-4092",
    ticket_number: "T-4092",
    customer_id: "cust-1",
    customer: {
      id: "cust-1",
      full_name: "Robert Downey",
      phone_number: "9876543210",
      customer_photo_url: "",
    },
    loan_amount: "1200.00",
    original_loan_amount: "1200.00",
    interest_rate: 3.0,
    adv_amount: 150.0,
    status: "active",
    pawned_date: "2026-08-12T00:00:00.000Z",
    due_date: "2026-11-12T00:00:00.000Z",
    items: [
      {
        id: "item-1",
        name: "22K Gold Figaro Chain",
        type: "gold",
        weight_grams: 22.4,
        purity: 91.6,
        description: "Hallmark stamped, 24-inch length, lobster claw clasp.",
        item_photo_url: "",
      },
    ],
  },
  {
    id: "pt-4091",
    ticket_number: "T-4091",
    customer_id: "cust-2",
    customer: {
      id: "cust-2",
      full_name: "Sophia Martinez",
      phone_number: "9845123456",
      customer_photo_url: "",
    },
    loan_amount: "3500.00",
    original_loan_amount: "3500.00",
    interest_rate: 2.5,
    adv_amount: 350.0,
    status: "active",
    pawned_date: "2026-08-05T00:00:00.000Z",
    due_date: "2026-11-05T00:00:00.000Z",
    items: [
      {
        id: "item-2",
        name: "Diamond Solitaire Ring (1.2ct)",
        type: "diamond",
        weight_grams: 5.8,
        purity: 75.0,
        description: "18K White gold band with 1.2 carat round brilliant diamond, VVS2 clarity.",
        item_photo_url: "",
      },
    ],
  },
  {
    id: "pt-3921",
    ticket_number: "T-3921",
    customer_id: "cust-3",
    customer: {
      id: "cust-3",
      full_name: "David Miller",
      phone_number: "9712345678",
      customer_photo_url: "",
    },
    loan_amount: "800.00",
    original_loan_amount: "800.00",
    interest_rate: 3.5,
    adv_amount: 100.0,
    status: "settled",
    pawned_date: "2026-06-10T00:00:00.000Z",
    settled_date: "2026-08-20T00:00:00.000Z",
    items: [
      {
        id: "item-3",
        name: "Sterling Silver Antique Tea Set",
        type: "silver",
        weight_grams: 480.0,
        purity: 92.5,
        description: "4-piece Edwardian silver set with hallmarks.",
        item_photo_url: "",
      },
    ],
  },
  {
    id: "pt-3880",
    ticket_number: "T-3880",
    customer_id: "cust-4",
    customer: {
      id: "cust-4",
      full_name: "Clara Oswald",
      phone_number: "9654321876",
      customer_photo_url: "",
    },
    loan_amount: "650.00",
    original_loan_amount: "650.00",
    interest_rate: 3.0,
    adv_amount: 80.0,
    status: "active",
    pawned_date: "2026-07-28T00:00:00.000Z",
    due_date: "2026-10-28T00:00:00.000Z",
    items: [
      {
        id: "item-4",
        name: "24K Gold Sovereign Bullion Coin",
        type: "gold",
        weight_grams: 8.0,
        purity: 99.9,
        description: "Mint condition bullion coin in protective acrylic capsule.",
        item_photo_url: "",
      },
    ],
  },
  {
    id: "pt-3742",
    ticket_number: "T-3742",
    customer_id: "cust-5",
    customer: {
      id: "cust-5",
      full_name: "James Wilson",
      phone_number: "9543216789",
      customer_photo_url: "",
    },
    loan_amount: "2100.00",
    original_loan_amount: "2100.00",
    interest_rate: 3.0,
    adv_amount: 250.0,
    status: "overdue",
    pawned_date: "2026-05-10T00:00:00.000Z",
    due_date: "2026-08-10T00:00:00.000Z",
    items: [
      {
        id: "item-5",
        name: "Swiss Chronograph Automatic Watch",
        type: "other",
        weight_grams: 145.0,
        purity: null,
        description: "Stainless steel case, sapphire crystal, original box included.",
        item_photo_url: "",
      },
    ],
  },
];

export const devPayments = [
  {
    id: "pay-1",
    ticket_id: "pt-4092",
    ticket_number: "T-4092",
    customer_name: "Robert Downey",
    payment_for: "interest",
    amount_paid: 36.0,
    payment_date: "2026-08-25T10:45:00.000Z",
    payment_method: "Cash",
    staff_name: "Alexander Wright",
  },
  {
    id: "pay-2",
    ticket_id: "pt-4091",
    ticket_number: "T-4091",
    customer_name: "Sophia Martinez",
    payment_for: "interest",
    amount_paid: 87.5,
    payment_date: "2026-08-20T14:30:00.000Z",
    payment_method: "UPI / Bank Transfer",
    staff_name: "Sarah Jenkins",
  },
  {
    id: "pay-3",
    ticket_id: "pt-3921",
    ticket_number: "T-3921",
    customer_name: "David Miller",
    payment_for: "principal",
    amount_paid: 800.0,
    payment_date: "2026-08-20T11:15:00.000Z",
    payment_method: "Cash",
    staff_name: "Alexander Wright",
  },
  {
    id: "pay-4",
    ticket_id: "pt-3921",
    ticket_number: "T-3921",
    customer_name: "David Miller",
    payment_for: "interest",
    amount_paid: 56.0,
    payment_date: "2026-08-20T11:15:00.000Z",
    payment_method: "Cash",
    staff_name: "Alexander Wright",
  },
];

export const devEmployees = [
  {
    id: "emp-1",
    firstName: "Alexander",
    lastName: "Wright",
    email: "alexander@grivi.io",
    username: "alexander",
    role: "manager",
    phone: "+1 (555) 234-8921",
    isActive: true,
  },
  {
    id: "emp-2",
    firstName: "Sarah",
    lastName: "Jenkins",
    email: "sarah.j@grivi.io",
    username: "sarahj",
    role: "cashier",
    phone: "+1 (555) 345-6789",
    isActive: true,
  },
  {
    id: "emp-3",
    firstName: "Marcus",
    lastName: "Vance",
    email: "marcus.v@grivi.io",
    username: "marcusv",
    role: "auditor",
    phone: "+1 (555) 456-7890",
    isActive: true,
  },

];

export const devRoles = [
  { id: "role-1", name: "manager", description: "Full operational access and rate editing" },
  { id: "role-2", name: "cashier", description: "Counter ticket generation and payment receipting" },
  { id: "role-3", name: "auditor", description: "Read-only financial and ledger reports" },
];

export const devNotifications = [
  {
    id: "notif-1",
    title: "Overdue Loan Alert",
    message: "Ticket #T-3742 (James Wilson, $2,100.00) is now 19 days overdue. Review grace period or initiate collateral notice.",
    type: "warning",
    createdAt: "2026-08-29T08:30:00.000Z",
    isRead: false,
    actionUrl: "/pawn-tickets/pt-3742",
  },
  {
    id: "notif-2",
    title: "Upcoming Due Date",
    message: "Ticket #T-4091 (Sophia Martinez) interest payment is due in 3 days ($87.50).",
    type: "info",
    createdAt: "2026-08-28T14:10:00.000Z",
    isRead: false,
    actionUrl: "/pawn-tickets/pt-4091",
  },
  {
    id: "notif-3",
    title: "Successful Redemption",
    message: "Ticket #T-3921 has been marked as fully settled and redeemed by David Miller.",
    type: "success",
    createdAt: "2026-08-20T11:20:00.000Z",
    isRead: true,
    actionUrl: "/pawn-tickets/pt-3921",
  },
  {
    id: "notif-4",
    title: "System Security Audit",
    message: "Daily encrypted database snapshot successfully completed at 02:00 AM.",
    type: "neutral",
    createdAt: "2026-08-29T02:00:00.000Z",
    isRead: true,
    actionUrl: "/settings",
  },
];
